---
- name: Generate template
  hosts: localhost
  tasks:
  - name: value1 tag is incorrect
    fail:
      msg: "Label mismatch"
    when: value1!="valueone"
  - name: Failed due to wrong NS
    fail:
      msg: "NS is not default NS"
    when: ns!="default"
  - name: App id is wrong
    fail:
      msg: " Please check your app id"
    when: AppID!="T001"
  - name: Generate pod template
    template:
      src: pod.yaml.j2
      dest: ./pod.yaml
